name: Build and test symengine
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    name: "${{ matrix.BUILD_TYPE }}-${{ matrix.OS }}-${{ matrix.CC }} (${{ toJSON(matrix) }})"
    strategy:
      fail-fast: false
      matrix:
        include:
          - BUILD_TYPE: Debug
            WITH_BFD: yes
            WITH_LATEST_GCC: yes
            WITH_COVERAGE: yes
            WITH_MPC: yes
            USE_GLIBCXX_DEBUG: yes
            OS: ubuntu-22.04
            CC: gcc
            EXTRA_APT_PACKAGES: g++-12 gcc-12

          - BUILD_TYPE: Debug
            WITH_BFD: yes
            WITH_COVERAGE: yes
            TEST_IN_TREE: yes
            WITH_FLINT: yes
            WITH_FLINT_DEV: yes
            WITH_MPC: yes
            CC: gcc
            OS: ubuntu-22.04

            # Debug build (with BFD)
          - BUILD_TYPE: Debug
            WITH_BFD: yes
            OS: ubuntu-22.04
            CC: gcc

          # Debug build (with BFD and SYMENGINE_THREAD_SAFE)
          - BUILD_TYPE: Debug
            WITH_BFD: yes
            WITH_SYMENGINE_THREAD_SAFE: yes
            OS: ubuntu-22.04
            CC: gcc

          # Debug build (with BFD, ECM, PRIMESIEVE and MPC)
          - BUILD_TYPE: Debug
            WITH_BFD: yes
            WITH_ECM: yes
            WITH_PRIMESIEVE: yes
            WITH_MPC: yes
            OS: ubuntu-22.04
            CC: gcc

          # Debug build (with BFD, Flint and Arb and INTEGER_CLASS from flint)
          - BUILD_TYPE: Debug
            WITH_BFD: yes
            WITH_ARB: yes
            INTEGER_CLASS: flint
            WITH_MPC: yes
            TEST_IN_TREE: yes
            OS: ubuntu-22.04
            CC: gcc

          # Debug build (with BFD, MPFR and INTEGER_CLASS from gmpxx)
          - BUILD_TYPE: Debug
            WITH_SYMENGINE_RCP: yes
            WITH_MPFR: yes
            INTEGER_CLASS: gmpxx
            OS: ubuntu-22.04
            CC: gcc

          # Debug build (with BFD and INTEGER_CLASS from boostmp)
          - BUILD_TYPE: Debug
            WITH_BFD: yes
            INTEGER_CLASS: boostmp
            OS: ubuntu-22.04
            WITH_LATEST_GCC: yes
            CC: gcc
            EXTRA_APT_PACKAGES: g++-12 gcc-12

          # Debug build shared lib (with BFD)
          - BUILD_TYPE: Debug
            WITH_BFD: yes
            BUILD_SHARED_LIBS: yes
            OS: ubuntu-22.04
            CC: gcc

          # Release build (with BFD)
          - WITH_BFD: yes
            OS: ubuntu-22.04
            CC: gcc

          # No-RTTI Release build
          - NO_RTTI: yes
            OS: ubuntu-22.04
            CC: gcc

          # Release shared build (with BFD)
          - WITH_BFD: yes
            BUILD_SHARED_LIBS: yes
            OS: ubuntu-22.04
            CC: gcc

          # Release build (recent LLVM)
          - BUILD_TYPE: Release
            OS: ubuntu-22.04
            CC: clang
            WITH_LLVM: 13
            EXTRA_APT_REPOSITORY: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main'
            EXTRA_APT_PACKAGES: clang-13 llvm-13

          # Release build (recent LLVM + clang)
          - BUILD_TYPE: Release
            OS: ubuntu-24.04
            CC: clang-18
            CXX: clang++-18
            WITH_LLVM: 18
            EXTRA_APT_REPOSITORY: 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-18 main'
            EXTRA_APT_PACKAGES: clang-18 llvm-18

          # Release build (latest pre-release of LLVM)
          - BUILD_TYPE: Release
            OS: ubuntu-24.04
            CC: clang
            WITH_LLVM: "LATEST"
            EXTRA_APT_REPOSITORY: 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble main'
            EXTRA_APT_PACKAGES: llvm

          ## In-tree builds (we just check a few configurations to make sure they work):
          # Debug build
          - BUILD_TYPE: Debug
            WITH_BFD: yes
            TEST_IN_TREE: yes
            OS: ubuntu-22.04
            CC: gcc

          - BUILD_TYPE: Debug
            WITH_BFD: yes
            WITH_PIRANHA: yes
            BUILD_SHARED_LIBS: yes
            CC: gcc
            OS: ubuntu-22.04

          - BUILD_TYPE: Debug
            WITH_BFD: yes
            WITH_PIRANHA: yes
            INTEGER_CLASS: piranha
            CC: gcc
            OS: ubuntu-22.04

          - BUILD_TYPE: Debug
            WITH_BFD: yes
            WITH_LLVM: 12
            WITH_COVERAGE: yes
            CC: clang
            OS: ubuntu-22.04

          - BUILD_TYPE: Release
            WITH_BENCHMARKS: yes
            WITH_BENCHMARKS_GOOGLE: yes
            WITH_LLVM: 14
            CC: clang
            OS: ubuntu-22.04

          - BUILD_TYPE: Debug
            WITH_LLVM: 5.0
            OS: macos-13
            CC: clang

          - BUILD_TYPE: Release
            WITH_LLVM: 5.0
            OS: macos-13
            CC: clang

          - BUILD_TYPE: Debug
            OS: macos-13
            CC: gcc

          - BUILD_TYPE: Release
            OS: macos-13
            CC: gcc

          - BUILD_TYPE: Debug
            WITH_SANITIZE: address
            WITH_LLVM: 12
            WITH_COTIRE: no
            CC: clang
            OS: ubuntu-22.04

          - BUILD_TYPE: Debug
            WITH_SANITIZE: undefined
            WITH_LLVM: 12
            CC: clang
            OS: ubuntu-22.04

          - BUILD_TYPE: Debug
            WITH_SANITIZE: thread
            WITH_SYMENGINE_THREAD_SAFE: yes
            OS: ubuntu-24.04
            CC: clang-18
            CXX: clang++-18
            WITH_LLVM: 18
            EXTRA_APT_REPOSITORY: 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-18 main'
            EXTRA_APT_PACKAGES: clang-18 llvm-18

          - BUILD_TYPE: Debug
            WITH_SANITIZE: memory
            WITH_SYMENGINE_RCP: yes
            WITH_BFD: no
            WITH_COTIRE: no
            EXTRA_APT_REPOSITORY: 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main'
            EXTRA_APT_PACKAGES: clang-15
            INTEGER_CLASS: boostmp
            CC: clang
            OS: ubuntu-22.04

          - MSYS_ENV: UCRT64
            ARCH: x86_64
            OS: windows-latest
            BUILD_TYPE: Release

          - MSYS_ENV: UCRT64
            ARCH: x86_64
            OS: windows-latest
            BUILD_TYPE: Debug

          - ARCH: x64
            OS: windows-latest
            BUILD_TYPE: Release
            WITH_MPC: yes
            WITH_MPFR: yes

          - ARCH: x64
            OS: windows-latest
            BUILD_TYPE: Release
            WITH_MPC: yes
            WITH_MPFR: yes
            BUILD_SHARED_LIBS: yes

          - ARCH: x64
            OS: windows-latest
            BUILD_TYPE: Release
            WITH_MPC: yes
            WITH_MPFR: yes
            WITH_FLINT: yes

          - ARCH: x64
            OS: windows-latest
            BUILD_TYPE: Release
            INTEGER_CLASS: boostmp

          - ARCH: x64
            OS: windows-latest
            BUILD_TYPE: Debug

    env:
      USE_GLIBCXX_DEBUG: ${{ matrix.USE_GLIBCXX_DEBUG }}
      WITH_MPFR: ${{ matrix.WITH_MPFR }}
      WITH_LLVM: ${{ matrix.WITH_LLVM }}
      WITH_BENCHMARKS: ${{ matrix.WITH_BENCHMARKS }}
      WITH_BENCHMARKS_GOOGLE: ${{ matrix.WITH_BENCHMARKS_GOOGLE }}
      WITH_SYMENGINE_RCP: ${{ matrix.WITH_SYMENGINE_RCP }}
      TEST_IN_TREE: ${{ matrix.TEST_IN_TREE }}
      WITH_SYMENGINE_THREAD_SAFE: ${{ matrix.WITH_SYMENGINE_THREAD_SAFE }}
      WITH_PRIMESIEVE: ${{ matrix.WITH_PRIMESIEVE }}
      INTEGER_CLASS: ${{ matrix.INTEGER_CLASS }}
      WITH_ARB: ${{ matrix.WITH_ARB }}
      WITH_PIRANHA: ${{ matrix.WITH_PIRANHA }}
      WITH_BFD: ${{ matrix.WITH_BFD }}
      WITH_FLINT: ${{ matrix.WITH_FLINT }}
      EXTRA_APT_REPOSITORY: ${{ matrix.EXTRA_APT_REPOSITORY }}
      EXTRA_APT_PACKAGES: ${{ matrix.EXTRA_APT_PACKAGES }}
      WITH_ECM: ${{ matrix.WITH_ECM }}
      WITH_LATEST_GCC: ${{ matrix.WITH_LATEST_GCC }}
      OS: ${{ matrix.OS }}
      WITH_FLINT_DEV: ${{ matrix.WITH_FLINT_DEV }}
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      WITH_COTIRE: ${{ matrix.WITH_COTIRE }}
      WITH_COVERAGE: ${{ matrix.WITH_COVERAGE }}
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      WITH_SANITIZE: ${{ matrix.WITH_SANITIZE }}
      WITH_MPC: ${{ matrix.WITH_MPC }}
      BUILD_SHARED_LIBS: ${{ matrix.BUILD_SHARED_LIBS }}
      NO_RTTI: ${{ matrix.NO_RTTI }}
      MSYS_ENV: ${{ matrix.MSYS_ENV }}
      OPTIONS: ${{ matrix.BUILD_TYPE }}-${{ matrix.OS }}-${{ matrix.CC }}-${{ matrix.USE_GLIBCXX_DEBUG }}-${{ matrix.WITH_MPFR }}-${{ matrix.WITH_LLVM }}-${{ matrix.WITH_BENCHMARKS }}-${{ matrix.WITH_BENCHMARKS_GOOGLE }}-${{ matrix.WITH_SYMENGINE_RCP }}-${{ matrix.TEST_IN_TREE }}-${{ matrix.WITH_SYMENGINE_THREAD_SAFE }}-${{ matrix.WITH_PRIMESIEVE }}-${{ matrix.INTEGER_CLASS }}-${{ matrix.WITH_ARB }}-${{ matrix.WITH_PIRANHA }}-${{ matrix.WITH_BFD }}-${{ matrix.WITH_FLINT }}-${{ matrix.WITH_ECM }}-${{ matrix.WITH_LATEST_GCC }}-${{ matrix.WITH_FLINT_DEV }}-${{ matrix.WITH_COTIRE }}-${{ matrix.WITH_COVERAGE }}-${{ matrix.WITH_SANITIZE }}-${{ matrix.WITH_MPC }}-${{ matrix.BUILD_SHARED_LIBS }}-${{ matrix.NO_RTTI }}-${{ matrix.MSYS_ENV }}
      CCACHE_DIR: 'D:\a\_temp\msys\msys64\home\runneradmin\.ccache'

    steps:
    - name: Setup msys2
      uses: msys2/setup-msys2@v2
      if: matrix.MSYS_ENV != ''
      with:
        msystem: ${{ matrix.MSYS_ENV }}
        update: true
        install: mingw-w64-ucrt-${{ matrix.ARCH }}-gcc mingw-w64-ucrt-${{ matrix.ARCH }}-cmake mingw-w64-ucrt-${{ matrix.ARCH }}-ccache python make git

    - name: Set ccache dir
      if: matrix.MSYS_ENV == ''
      run: echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

    - uses: conda-incubator/setup-miniconda@v3
      if: matrix.MSYS_ENV == ''
      with:
        activate-environment: symengine
        channel-priority: strict
        architecture: ${{ matrix.ARCH }}
        channels: conda-forge
        conda-remove-defaults: "true"

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.job }}-${{ env.OPTIONS }}-${{ runner.os }}-${{ github.sha }}
        restore-keys: ccache-${{ github.job }}-${{ env.OPTIONS }}-${{ runner.os }}-

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Build and test symengine
      shell: msys2 {0}
      if: matrix.MSYS_ENV != ''
      run: ./bin/test_symengine.sh

    - name: Build and test symengine
      shell: bash -el {0}
      if: matrix.MSYS_ENV == ''
      run: source ./bin/test_symengine.sh

  matchpycpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          environment-file: symengine/utilities/matchpycpp/environment.yml
      - shell: bash -el {0}
        run: ./bin/test_matchpycpp_gen_tests.sh

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install "clang-format==11.1.0.2" && ./bin/run_clang_format.sh

  check:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
