name: Build and test symengine
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.OS }}
    name: "${{ matrix.BUILD_TYPE }}-${{ matrix.OS }}-${{ matrix.CC }} (${{ toJSON(matrix) }})"
    strategy:
      fail-fast: false
      matrix:
        include:

          # DO-NOT-MERGE! Pruned for efficiency while debugging CI config

          - BUILD_TYPE: Debug
            OS: macos-13
            CC: gcc

          - BUILD_TYPE: Release
            OS: macos-13
            CC: gcc

    env:
      USE_GLIBCXX_DEBUG: ${{ matrix.USE_GLIBCXX_DEBUG }}
      WITH_MPFR: ${{ matrix.WITH_MPFR }}
      WITH_LLVM: ${{ matrix.WITH_LLVM }}
      WITH_BENCHMARKS: ${{ matrix.WITH_BENCHMARKS }}
      WITH_BENCHMARKS_GOOGLE: ${{ matrix.WITH_BENCHMARKS_GOOGLE }}
      WITH_SYMENGINE_RCP: ${{ matrix.WITH_SYMENGINE_RCP }}
      TEST_IN_TREE: ${{ matrix.TEST_IN_TREE }}
      WITH_SYMENGINE_THREAD_SAFE: ${{ matrix.WITH_SYMENGINE_THREAD_SAFE }}
      WITH_PRIMESIEVE: ${{ matrix.WITH_PRIMESIEVE }}
      INTEGER_CLASS: ${{ matrix.INTEGER_CLASS }}
      WITH_ARB: ${{ matrix.WITH_ARB }}
      WITH_PIRANHA: ${{ matrix.WITH_PIRANHA }}
      WITH_BFD: ${{ matrix.WITH_BFD }}
      WITH_FLINT: ${{ matrix.WITH_FLINT }}
      EXTRA_APT_REPOSITORY: ${{ matrix.EXTRA_APT_REPOSITORY }}
      EXTRA_APT_PACKAGES: ${{ matrix.EXTRA_APT_PACKAGES }}
      WITH_ECM: ${{ matrix.WITH_ECM }}
      WITH_LATEST_GCC: ${{ matrix.WITH_LATEST_GCC }}
      OS: ${{ matrix.OS }}
      WITH_FLINT_DEV: ${{ matrix.WITH_FLINT_DEV }}
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      WITH_COTIRE: ${{ matrix.WITH_COTIRE }}
      WITH_COVERAGE: ${{ matrix.WITH_COVERAGE }}
      BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      WITH_SANITIZE: ${{ matrix.WITH_SANITIZE }}
      WITH_MPC: ${{ matrix.WITH_MPC }}
      BUILD_SHARED_LIBS: ${{ matrix.BUILD_SHARED_LIBS }}
      NO_RTTI: ${{ matrix.NO_RTTI }}
      MSYS_ENV: ${{ matrix.MSYS_ENV }}
      OPTIONS: ${{ matrix.BUILD_TYPE }}-${{ matrix.OS }}-${{ matrix.CC }}-${{ matrix.USE_GLIBCXX_DEBUG }}-${{ matrix.WITH_MPFR }}-${{ matrix.WITH_LLVM }}-${{ matrix.WITH_BENCHMARKS }}-${{ matrix.WITH_BENCHMARKS_GOOGLE }}-${{ matrix.WITH_SYMENGINE_RCP }}-${{ matrix.TEST_IN_TREE }}-${{ matrix.WITH_SYMENGINE_THREAD_SAFE }}-${{ matrix.WITH_PRIMESIEVE }}-${{ matrix.INTEGER_CLASS }}-${{ matrix.WITH_ARB }}-${{ matrix.WITH_PIRANHA }}-${{ matrix.WITH_BFD }}-${{ matrix.WITH_FLINT }}-${{ matrix.WITH_ECM }}-${{ matrix.WITH_LATEST_GCC }}-${{ matrix.WITH_FLINT_DEV }}-${{ matrix.WITH_COTIRE }}-${{ matrix.WITH_COVERAGE }}-${{ matrix.WITH_SANITIZE }}-${{ matrix.WITH_MPC }}-${{ matrix.BUILD_SHARED_LIBS }}-${{ matrix.NO_RTTI }}-${{ matrix.MSYS_ENV }}
      CCACHE_DIR: 'D:\a\_temp\msys\msys64\home\runneradmin\.ccache'

    steps:
    - name: Setup msys2
      uses: msys2/setup-msys2@v2
      if: matrix.MSYS_ENV != ''
      with:
        msystem: ${{ matrix.MSYS_ENV }}
        update: true
        install: mingw-w64-ucrt-${{ matrix.ARCH }}-gcc mingw-w64-ucrt-${{ matrix.ARCH }}-cmake mingw-w64-ucrt-${{ matrix.ARCH }}-ccache python make git

    - name: Set ccache dir
      if: matrix.MSYS_ENV == ''
      run: echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

    - uses: conda-incubator/setup-miniconda@v3
      if: matrix.MSYS_ENV == ''
      with:
        activate-environment: symengine
        channel-priority: strict
        architecture: ${{ matrix.ARCH }}
        channels: conda-forge
        conda-remove-defaults: "true"

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.job }}-${{ env.OPTIONS }}-${{ runner.os }}-${{ github.sha }}
        restore-keys: ccache-${{ github.job }}-${{ env.OPTIONS }}-${{ runner.os }}-

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Build and test symengine
      shell: msys2 {0}
      if: matrix.MSYS_ENV != ''
      run: ./bin/test_symengine.sh

    - name: Build and test symengine
      shell: bash -el {0}
      if: matrix.MSYS_ENV == ''
      run: source ./bin/test_symengine.sh

  matchpycpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          environment-file: symengine/utilities/matchpycpp/environment.yml
      - shell: bash -el {0}
        run: ./bin/test_matchpycpp_gen_tests.sh

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install "clang-format==11.1.0.2" && ./bin/run_clang_format.sh

  check:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
